/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 scene.gltf 
Author: Polutopia (https://sketchfab.com/Polutopia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sock-416ccf5921d44a1690b77f6f5c0fabfd
Title: Sock
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Rib_2X2_468gsm_FRONT_2859} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Rib_2X2_468gsm_FRONT_2859.001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Rib_2X2_468gsm_FRONT_2859.002']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Object_8.geometry} material={materials['Rib_2X2_468gsm_FRONT_2859.003']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Rib_2X2_468gsm_FRONT_2859.004']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Rib_2X2_468gsm_FRONT_2859.005']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Object_12.geometry} material={materials['Rib_2X2_468gsm_FRONT_2859.006']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Rib_2X2_468gsm_FRONT_2859.007']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Rib_2X2_468gsm_FRONT_2859.008']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Object_16.geometry} material={materials.Knit_Ponte_Jersey_FRONT_2871} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['Knit_Ponte_Jersey_FRONT_2871.001']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['Knit_Ponte_Jersey_FRONT_2871.002']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Object_20.geometry} material={materials['Rib_2X2_468gsm_FRONT_2859.009']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['Rib_2X2_468gsm_FRONT_2859.010']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['Rib_2X2_468gsm_FRONT_2859.011']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Object_24.geometry} material={materials['Rib_2X2_468gsm_FRONT_2859.012']} />
        <mesh geometry={nodes.Object_25.geometry} material={materials['Rib_2X2_468gsm_FRONT_2859.013']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['Rib_2X2_468gsm_FRONT_2859.014']} />
      </group>
      <mesh geometry={nodes.Object_28.geometry} material={materials.PT_FABRIC_FRONT_6052} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
