/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 sock.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sock.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_Cube001.geometry} material={nodes.Cube_Cube001.material} />
    </group>
  )
}

useGLTF.preload('/sock.gltf')
